export const SET_TX_START = "SET_TX_START";
export const SET_TX_ERROR = "SET_TX_ERROR";
export const SET_TX_END = "SET_TX_END";
export const SET_DRIZZLE = "SET_DRIZZLE";
export const SET_SUBSCRIPTION_VALUE = "SET_SUBSCRIPTION_VALUE";
export const INCREMENT_INDEX = "INCREMENT_INDEX";
export const DECREMENT_INDEX = "DECREMENT_INDEX";
export const SET_SUBSCRIPTION_CHANNEL = "SET_SUBSCRIPTION_CHANNEL";
